services:
  cloudshell_eks:
    build: .
    container_name: cloudshell_eks
    volumes:
      - .:/apps/cloudshell
      - ~/development:/apps/development
      - ~/.aws:/root/.aws
      - ~/.kube:/root/.kube
      - ~/.claude:/root/.claude
    env_file: .env